.TH AIRRECON 1 "December 2025" "airRecon" "User Commands"

.SH NAME
airRecon \- Rogue AP - Evil Twin

.SH SYNOPSIS
.B airRecon
[\-i interface] [\-l logdir] [\-s]

.SH DESCRIPTION
airRecon is an educational Wi-Fi reconnaissance tool.
It captures Wi-Fi beacons, to clone an angel wireless network into an evil twin.
Allows you to capture and analyse network traffic. 

.SH OPTIONS
.TP
.B \-i, \-\-iface
Wireless interface in monitor mode.

.TP
.B \-l, \-\-log-dir
Directory to store logs and captures.

.TP
.B \-s, \-\-scan
Perform a live Wi-Fi scan.

.TP
.B \-h, \-\-help
Display help.

.SH NOTES
This tool is intended for educational use on authorized networks only.

.SH AUTHOR
Rafael & Ahmed
